### ISSUE TITLE
Application not working on Touchscreen

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC#49] opened 2020-01-20 19:41 UTC
This issue is raised here https://forum.groupdocs.com/t/annotations-not-working-on-touchscreen/7950.

Hi,
Application works fine using mouse, but for touchscreen it does not seem to be working. It looks like its not detecting the touch drag movements and/or the touch clicks correctly. Have a look at this video https://streamable.com/qtlkm.

Thanks

**Comment by kegor** [comment] 2020-01-24 11:08
Hi @atirtahirgroupdocs, we were able to reproduce this problem and are working on a solution.

**Comment by pro-tian** [comment] 2020-01-30 20:13
Hello @kegor, any updates or estimated time for fix? Thanks

**Comment by bobkovalex** [comment] 2020-02-05 13:40
@pro-tian 

I apologise for not replying sooner.

The issue will be fixed in next public release which is expected in 1-2 weeks from now due to massive product update.

I'll notify you when release is complete.

**Comment by bobkovalex** [comment] 2020-02-12 14:26
@pro-tian @atirtahirgroupdocs 

The issue has been fixed.
Just pull latest commit from master branch.

**Please note** that now GroupDocs.Annotation for .NET MCV uses Angular instead of jQuery.
jQuery has been discontinued.

Regards.

**Closed by bobkovalex** 2020-02-12 14:26 UTC
Labels: bug, enhancement

**Comment by pro-tian** [comment] 2020-02-12 15:35
@bobkovalex 

Hello, I'm unable to build the latest:

![image](https://user-images.githubusercontent.com/16791669/74350084-34cb1380-4d83-11ea-877c-29b07dab9acf.png)

This is the output log:
![image](https://user-images.githubusercontent.com/16791669/74350182-575d2c80-4d83-11ea-9c60-ef97c9daba81.png)

**Comment by bobkovalex** [comment] 2020-02-12 20:21
@pro-tian 

Hello,

We are unable to reproduce your issue, could you please provide more information on your environment, tools you are using, etc?
Logs from npm-cache also might be helpful.

By the way, are you running application as administrator?

Just to make sure that packages were fetched successfully, try cleaning up `/client/node_modules` and re-build from scratch.

Regards

**Comment by bobkovalex** [comment] 2020-02-13 11:04
@pro-tian 

I'm not sure if you have already resolved the issue, however following steps might help you:

1. Reinstall Node
2. Delete `node_modules` folder
3. Run `npm cache clean --force`
4. Remove `npm` and `npm-cache` folders from `C:\Users\{username}\AppData\Roaming`
5. Run `npm install -g @angular/cli@latest` and `npm i`
6. Build the solution in Visual Studio

Related issues:
https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms/issues/61
https://github.com/groupdocs-comparison/GroupDocs.Comparison-for-.NET-WebForms/issues/25

**Comment by pro-tian** [comment] 2020-02-18 14:39
@bobkovalex 

I was able to build it as administrator, thanks!

**Comment by pro-tian** [comment] 2020-02-18 14:41
However, I'm not able to deploy the application to IIS. I get blank white page when I try browsing.

**Comment by bobkovalex** [comment] 2020-02-19 09:02
@pro-tian 

Do you see any errors in browser console or in app console?
